name: Build and deploy

on:
  push:
    branches: [ main ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.5'
    - run: go version
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Run Mage
      uses: magefile/mage-action@v1
      with:
        version: latest
        args: -v
    - run: yarn install
    - run: yarn build
    - run: docker build -t octopussamples/grafana:latest -f ./Dockerfile ./dist
    - run: docker push octopussamples/grafana:latest
